version: "3.1"

services:
  web-client:
    build:
      context:
        ./apps/web-client
    hostname: "ssr.offensive.local"
    volumes:
      - ./apps/web-client:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=443
    container_name: web-client
    hostname: "ssr.offensive.local"

  proxy:
    build:
      context:
        ./apps/proxy
    ports:
      - 443:443
    volumes:
      - ./apps/proxy/certs:/etc/nginx/certs/
    container_name: offensive.local
    hostname: offensive.local
    depends_on:
      - web-client

  db:
    build:
      context:
        ./apps/db
    container_name: db
    hostname: db.offensive.local
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=offensive
      - POSTGRES_PASSWORD=testee
      - POSTGRES_DB=offensive

  go-server:
    build:
      context:
        ./apps/go-server
    hostname: "api.offensive.local"
    volumes:
      - ./apps/go-server:/usr/src/app
    container_name: api-server
    ports:
      - 7070:7070
      - 2345:2345
    security_opt:
      - seccomp:unconfined
    depends_on:
      - db
    environment:
      - PORT=7070
    entrypoint:
      - ./scripts/debug.sh
