version: "3.1"

services:
  web-client:
    build:
      context:
        ./apps/web-client
    hostname: "ssr.offensive.local"
    volumes:
      - ./apps/web-client:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=443
    container_name: web-client
    hostname: "ssr.offensive.local"

  proxy:
    build:
      context:
        ./apps/proxy
    ports: 
      - 443:443
    volumes:
      - ./apps/proxy/certs:/etc/nginx/certs/
    container_name: offensive.local
    hostname: offensive.local
    depends_on:
      - web-client

  demo-server:
    build:
      context:
        ./apps/demo-server
    hostname: "demo.offensive.local"
    volumes:
      - ./apps/demo-server:/usr/src/app
    container_name: demo-server
    environment:
      - NODE_ENV=development
      - PORT=7070
