version: "3.1"

services:
  web-client:
    build:
      context:
        ./apps/web-client
    ports:
      - 443:443
    volumes:
      - ./apps/web-client:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=443
